### ISSUE TITLE
Names That Do Not Translate

### ISSUE THREAD

**Issue by TechieSandan** [nolanlawson/JapaneseNameConverterRoot#2]
Glen (1 "n") and Betsy

**Comment by nolanlawson** [comment]
Confirmed, I can repro. It seems to be hitting an error.

**Comment by TechieSandan** [comment]
I just received this email from you this morning. Did this come through on a delay from the other day? Everything seems to be OK.

**Comment by TechieSandan** [comment]
Sorry, please disregard the last email. I thought it was from somebody else that helped me with the access program. Thank you!
