### ISSUE TITLE
Wrong translation of Stephen - a very common name

### ISSUE THREAD

**Issue by summitcomputing** [nolanlawson/JapaneseNameConverterRoot#3]
Stephen should be pronounced the same way as Steven

The app wrongly translates Stephen as ステフェン (sutefen) but correctly translates Steven as スティーブン (sutiibun)

Both spellings should result in the translation スティーブン (sutiibun)

**Comment by nolanlawson** [comment]
Thanks for the report. This is an ambiguous case – AFAIK, some people do pronounce it "steh-FEN".

Arguably the "v" pronunciation is more common though.

**Comment by summitcomputing** [comment]
Maybe it's regional, but I've never heard it pronounced that way. Please see https://youtu.be/aMW1UdelXbI or 
https://youtu.be/7pX-7IMTPjQ and many others. Thanks
